version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
    ports:
      - ${HTTP_API_PORT}:${HTTP_API_PORT}
  db:
    image: mysql:8.2.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test_task_database"
      MYSQL_USER: "test_task_user"
      MYSQL_PASSWORD: "test_task_password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      LANG: "C.UTF-8"
    volumes:
      - my-db:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
networks:
  default:
    name: rest_test
volumes:
  my-db:

