// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: auth.sql

package storage

import (
	"context"
)

const getApiKeyID = `-- name: GetApiKeyID :one
SELECT id FROM auth
WHERE api_key = ?
`

func (q *Queries) GetApiKeyID(ctx context.Context, apiKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyID, apiKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}
